### ISSUE TITLE
macOS version ... will donate to support

### ISSUE THREAD

**Issue by ahingston** [schellingb/UnityCapture#28]
Not an issue exactly ... but I'd love to see a version of this that works on a macOS Unity project (especially on Apple Silicon) for an education project that I'm working on right now. Happy to donate some funds towards achieving this. If anyone reading this is keen to attempt the project, please contact me at andrew.hingston@unsw.edu.au

**Comment by schellingb** [comment]
Everything in this project is Windows specific. The APIs used to make a virtual webcam via a custom direct draw filter is unique to Windows so there isn't really anything that could be used on another platform like macOS.
It might be easier to make an OBS plugin than trying to recreate what is being done here. Such a plugin would be exclusive to OBS but it could provide higher performance, better resolution, support for alpha channel and run on all platforms that OBS runs.

Personally it's been years since I had a need for UnityCapture and it has been almost as many years since I used Unity at all so I don't see myself working on this in the future. I'm open to contributions regarding compatibility or platform enhancements though.

**Comment by ahingston** [comment]
Thanks for replying. No problems. If anyone else is interested then please get in contact with me.
